# Generated by Django 4.0.4 on 2022-05-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='namePDF',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reportID',
            new_name='reportId',
        ),
    ]
