# Generated by Django 4.0.4 on 2022-05-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_namepdf_pdf_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportId',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
