# Generated by Django 4.0.4 on 2022-05-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_report_reportid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='base64',
            field=models.CharField(max_length=100000000000000000000000000000000000000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='githubURL',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
